name: Build and Deploy to Docker Hub

on:  # this mean when should this run 
  push: # it runs whenever the push code on master branch
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . # this means from where is the docker file comming from 
        file: ./docker/Dockerfile.user
        push: true
        tags: mayan155/week-18:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull mayan155/week-18:latest  # Replace with your Docker Hub username and repository
