
# These pipe lines we can goole how waht the actions i have to use and just copy it 




name: Build on PR   # frist we give the name 

on:   # this mean when should this run 
  pull_request:  # it runs whenever the pull-request is made 
    branches: # on any code base but we define master branch means   
      - master # if someone create an pull-request on master branch then run th ework flow if someone creates a pull request on diffrent branch dont runs this work flow 
      # - main here we can also add more branch  

jobs: 
  build: # we have to run a single job a build job 
    runs-on: ubuntu-latest # this job runs on this  ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # this will cloens the repository 
      - name: Use Node.js  # insall node.js on machine
        uses: actions/setup-node@v3
        with:
          node-version: '20' # version on node.js 
      
      - name: Install Dependencies # run's npm install
        run: npm install
      
      - name: Generate prisma client # this will generate the client prisma client
        run: npm run db:generate
        
      - name: Run Build
        run: npm run build
